# Generated by Django 4.2.19 on 2026-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userregistration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
